AWSTemplateFormatVersion: 2010-09-09
Description: |
  This template launches an ec2 instance w/ a SG which enables SSH.
Resources:
  CFNInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-01b799c439fd5516a
      InstanceType: t2.micro
      KeyName: guile # please use your key pair w/o .pem ext.
      SecurityGroups: 
        - !Ref CFNSecGr
      Tags: 
        - Key: Name
          Value: My-Cfn-Instance

  CFNSecGr:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allows SSH # Required
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
